.TH PYGROOT "1" "May 2015" "pygroot 1.0" "User Commands"
.SH NAME
pygroot \- manual page for pygroot 1.0
.SH SYNOPSIS
usage: pygroot [\-h] [\-\-version] FILE
.PP
.SH DESCRIPTION
The Groot Programming Language interpreter
.PP
.SH OPTIONS
.SS "positional arguments:"
.TP
FILE
path to the file with program on Groot
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-version\fR
show program's version number and exit
.SH "REPORTING BUGS"
Report bugs to: keldzh@gmail.com
.SH COPYRIGHT
Copyright \(co 2015 Anton Kovalyov
.br
License GPLv3: GNU GPL version 3 or later <http://www.gnu.org/licenses/gpl\-3.0.html>
.br
This program comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law.
This is free software, and you are welcome to redistribute it under certain conditions.
